### ISSUE TITLE
Feature Request: Multiple Specifications for Hub Sender [Not A Bug]

### ISSUE THREAD

**Issue by R00tB33rMan** [Elytrium/VelocityTools#5]
VelocityTools is very versatile and effective for large production networks that are desiring additional useful features for their networks.

In my opinion, this resource could be perfected by allowing the specification for multiple servers when executing /hub & /lobby, in acting as a load balancer to mitigate the use of other plugins, when this one could easily do this for us.

To visualize, it could look like this:
```
hub:
    enabled: true
    servers: ["Hub-1", "Hub-2", "Hub-3"]
    # Set to "" to disable.
    you-got-moved: "&aYou have been sent to a lobby."
    disabled-server: "&cThis server is currently unavailable."
    disabled-servers: 
    - "foo"
    - "bar"
    aliases: 
    - "hub"
    - "lobby"
```

I thank you for being so diligent in ensuring this resource is production-ready and hope to see this feature implemented. Thanks for reading! (I wasn't sure where else to post this).
